"""MACD 样例数据"""

MACD_SAMPLE_TOPIC = {
    "topic": "60秒带你搞懂MACD",
    "topic_type": "indicator",
    "audience": "beginner",
    "duration": 60,
    "platform": "douyin_wechat_channels",
    "visual_style": "black_gold",
    "risk_level": "education_only",
}

MACD_SAMPLE_STORYBOARD = {
    "title": "60秒搞懂MACD：金叉不是买入按钮",
    "scenes": [
        {
            "scene_id": "s1",
            "scene_type": "hook",
            "start": 0,
            "duration": 3,
            "title": "金叉就能买？",
            "subtitle": "新手最容易踩的坑",
            "bullets": [],
            "narration": "很多新手一看到MACD金叉，就想马上买。但这恰恰是最容易踩坑的地方。",
            "visual_style": "black_gold",
            "template_id": "hook_title",
            "chart_type": "none",
            "chart_hint": "深色背景，MACD金叉图形从背景中浮现",
            "risk_note": "",
        },
        {
            "scene_id": "s2",
            "scene_type": "misunderstanding",
            "start": 3,
            "duration": 5,
            "title": "它不是买卖按钮",
            "subtitle": "只是一个观察工具",
            "bullets": ["不是预测器", "不是指令", "只是辅助"],
            "narration": "MACD不是买卖按钮，它只是帮你观察趋势变化的工具。",
            "visual_style": "black_gold",
            "template_id": "myth_vs_truth",
            "chart_type": "macd",
            "chart_hint": "左侧误区，右侧正确理解",
            "risk_note": "",
        },
        {
            "scene_id": "s3",
            "scene_type": "concept",
            "start": 8,
            "duration": 10,
            "title": "MACD看趋势",
            "subtitle": "核心是快慢线变化",
            "bullets": ["DIF是快线", "DEA是慢线", "柱子看差距"],
            "narration": "简单理解，DIF是快线，DEA是慢线，红绿柱反映两条线之间的距离变化。",
            "visual_style": "black_gold",
            "template_id": "concept_card",
            "chart_type": "macd",
            "chart_hint": "分别标出DIF、DEA、红绿柱",
            "risk_note": "",
        },
        {
            "scene_id": "s4",
            "scene_type": "how_it_works",
            "start": 18,
            "duration": 14,
            "title": "红绿柱看变化",
            "subtitle": "柱子变长，说明差距扩大",
            "bullets": ["红柱增强", "绿柱减弱", "趋势变化"],
            "narration": "当红柱逐渐变长，通常说明向上的动能在增强；当绿柱变长，说明向下的压力在扩大。",
            "visual_style": "black_gold",
            "template_id": "indicator_chart",
            "chart_type": "macd",
            "chart_hint": "动态展示红绿柱由短变长",
            "risk_note": "",
        },
        {
            "scene_id": "s5",
            "scene_type": "how_to_use",
            "start": 32,
            "duration": 13,
            "title": "别只看金叉",
            "subtitle": "还要看这三件事",
            "bullets": ["趋势位置", "成交量", "风险空间"],
            "narration": "真正使用MACD时，不能只看金叉死叉，还要结合趋势位置、成交量和自己的风险空间。",
            "visual_style": "black_gold",
            "template_id": "three_points",
            "chart_type": "none",
            "chart_hint": "三张卡片依次出现",
            "risk_note": "",
        },
        {
            "scene_id": "s6",
            "scene_type": "pitfall",
            "start": 45,
            "duration": 10,
            "title": "高位金叉也会坑",
            "subtitle": "位置不同，意义不同",
            "bullets": ["低位不等于安全", "高位不等于机会", "指标会滞后"],
            "narration": "尤其要注意，MACD本身有滞后性。高位出现金叉，也不代表一定还能继续涨。",
            "visual_style": "black_gold",
            "template_id": "risk_warning",
            "chart_type": "macd",
            "chart_hint": "高位区域出现警示标记，不写买卖字样",
            "risk_note": "指标存在滞后性",
        },
        {
            "scene_id": "s7",
            "scene_type": "summary",
            "start": 55,
            "duration": 5,
            "title": "一句话记住",
            "subtitle": "MACD看趋势，不预测未来",
            "bullets": [],
            "narration": "一句话记住，MACD看的是趋势变化，不是预测未来，更不能单独作为买卖依据。",
            "visual_style": "black_gold",
            "template_id": "summary_quote",
            "chart_type": "none",
            "chart_hint": "金句居中，底部显示风险提示",
            "risk_note": "仅作知识科普，不构成投资建议",
        },
    ],
}
